Upgrade lsp4ij to 0.19.1 to fix ArrayIndexOutOfBoundsException
Fix for semantic tokens highlighting crash when loading plugin in IDE.

The error occurred in lsp4ij 0.9.0's LSPSemanticTokensHighlightVisitor
trying to access index 27756 in an array of length 27756 (off-by-one bug).

Upgrading to lsp4ij 0.19.1 resolves this issue.

Error trace:
  ArrayIndexOutOfBoundsException: Index 27756 out of bounds for length 27756
  at LSPSemanticTokensHighlightVisitor.lambda$highlightSemanticTokens$1
  at SemanticTokensData.highlight